//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BO
    {
        public BO()
        {
            this.ChiTietQuyTrinhs = new HashSet<ChiTietQuyTrinh>();
        }
    
        public int MaSoChip { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> CanNang { get; set; }
        public string MauSac { get; set; }
        public string DacDiemNhanDien { get; set; }
        public Nullable<bool> DiTat { get; set; }
    
        public virtual ICollection<ChiTietQuyTrinh> ChiTietQuyTrinhs { get; set; }
    }
}
