//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkSmile_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cow
    {
        public int cowsCode { get; set; }
        public Nullable<int> weight { get; set; }
        public string color { get; set; }
        public string characteristics { get; set; }
        public Nullable<bool> goesOff { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
