//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkSmile_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_Cows
    {
        public int chipCode { get; set; }
        public Nullable<System.TimeSpan> date { get; set; }
        public Nullable<int> temperature { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> protit { get; set; }
        public Nullable<int> gluxit { get; set; }
        public Nullable<int> lipit { get; set; }
        public string healthStatus { get; set; }
    }
}
