//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkSmile_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lodging
    {
        public int lodgingCode { get; set; }
        public Nullable<int> locationCode { get; set; }
        public string addres { get; set; }
    }
}
