//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkSmile_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poster
    {
        public int employeeCode { get; set; }
        public string fullName { get; set; }
        public string address { get; set; }
        public Nullable<int> identityCode { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    }
}
