//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSUCKHOE
    {
        public int MaSoChip { get; set; }
        public System.DateTime NgayGhiNhan { get; set; }
        public Nullable<System.TimeSpan> GioGhiNhan { get; set; }
        public Nullable<int> CanNang { get; set; }
        public Nullable<int> NhietDo { get; set; }
        public Nullable<int> Protit { get; set; }
        public Nullable<int> Gluxit { get; set; }
        public Nullable<int> Lipit { get; set; }
        public string TTSucKhoe { get; set; }
    }
}
