//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANPHOI
    {
        public int MaPhanPhoi { get; set; }
        public Nullable<int> MaNhaSX { get; set; }
        public Nullable<int> MaBonChua { get; set; }
        public Nullable<System.TimeSpan> NgayPP { get; set; }
    }
}
