//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSO
    {
        public int MaCS { get; set; }
        public string DiaChiCS { get; set; }
        public Nullable<int> MaTruSo { get; set; }
        public Nullable<int> NguoiQuanLy { get; set; }
    }
}
