//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTQUYTRINH
    {
        public int MaQuyTrinh { get; set; }
        public int MaSoChip { get; set; }
        public Nullable<int> SoLuongSua { get; set; }
        public string TinhTrangBauVu { get; set; }
    }
}
