//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mm.DataAccessLayer
{
    using DomainModel;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DrinkMilkEntities : DbContext
    {
        public DrinkMilkEntities()
            : base("name=DrinkMilkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BO> BOes { get; set; }
        public DbSet<ChiTietQuyTrinh> ChiTietQuyTrinhs { get; set; }
        public DbSet<CHUONG> CHUONGs { get; set; }
        public DbSet<COSO> COSOes { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<QUYTRINHVATSUA> QUYTRINHVATSUAs { get; set; }
        public DbSet<TRUSO> TRUSOes { get; set; }
    }
}
